name: Backend & Database CI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ add-docker ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      SECRET_KEY: GitHub-Actions-CI
      ALLOWED_HOSTS: localhost
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:8000,http://localhost
      MYSQL_READY: True
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: litte
      MYSQL_PASSWORD: devpass
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306

    services:
      mysql_db:
        image: mysql:9.3.0
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u root -p${{ env.MYSQL_ROOT_PASSWORD }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if missing migrations
        run: |
          python manage.py makemigrations --check

      - name: Run Tests
        run: |
          python manage.py test